### ISSUE TITLE
Migrate to Maven Central

### ISSUE THREAD

**Issue by costular** [motorro/AppUpdateWrapper#17]
Since JFrog has announced that they are shutting down JCenter where this library is uploaded to, would be great to migrate to Maven Central.

**Comment by motorro** [comment]
Thanks for the reminder! Already working on it :)

**Comment by motorro** [comment]
@costular, please check if you could download from mavenLocal. [Works](https://repo1.maven.org/maven2/com/motorro/appupdatewrapper/appupdatewrapper/1.6.3/) for me. 
Will need to setup CI scripts a bit later so the ticket stays open

**Comment by costular** [comment]
It works. Great work @motorro :)
