### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError Failed resolution of: Ltimber/log/Timber;

### ISSUE THREAD

**Issue by samvmisti** [motorro/AppUpdateWrapper#18]
Caused by java.lang.ClassNotFoundException: timber.log.Timber
       at com.motorro.appupdatewrapper.LogUtilsKt.getTimber(LogUtilsKt.java:56)
       at com.motorro.appupdatewrapper.AppUpdateLifecycleStateMachine.<init>(AppUpdateLifecycleStateMachine.java:72)
       at com.motorro.appupdatewrapper.AppUpdateLifecycleStateMachine.<init>(AppUpdateLifecycleStateMachine.java:61)
       at com.motorro.appupdatewrapper.ImmediateUpdateKt.startImmediateUpdate(ImmediateUpdateKt.java:39)

**Comment by samvmisti** [comment]
Got this crash while updating application. Version `com.motorro.appupdatewrapper:appupdatewrapper:1.6.2@aar`

**Comment by motorro** [comment]
@samvgorode 
1. Does it happen every time you launch?
2. Do you have [Timber](https://github.com/motorro/AppUpdateWrapper/blob/master/appupdatewrapper/build.gradle#L74) in your app dependencies?

I'm not sure I should change it to `api` in the library...

**Comment by samvmisti** [comment]
@motorro 
1. this happens every time when there is app update on devices: Samsung, Xiaomi, Huawei
2. no timber in our app

**Comment by samvmisti** [comment]
Maybe you can add some Timber check inside your library?

**Comment by motorro** [comment]
@samvgorode, I've created a sample app (see issue-18-no-timber branch). 
But I can't reproduce the issue even in release builds with proguard.
Could you please try it on your devices and apply your proguard config to try to reproduce?

**Comment by samvmisti** [comment]
@motorro thank you for the response. I'll test it.

**Comment by samvmisti** [comment]
@motorro can not reproduce with your sample. You can close the issue.

**Comment by motorro** [comment]
@samvgorode let it stay opened for a while in case you figure out the problem or anyone else report the same.
The only reason that comes to my mind is proguard somehow cleans Timber away 🤷‍♂️
