### ISSUE TITLE
Lifecycle annotation type

### ISSUE THREAD

**Issue by akniyetc** [motorro/AppUpdateWrapper#20]
Hello, there is a typo in the `AppUpdateLifecycleStateMachine`, annotation is wrong at the top of `onPause()` method
`@OnLifecycleEvent(ON_RESUME)
fun onPause() {
        currentUpdateState.onPause()
}`

`ON_RESUME` should be replaced with `ON_PAUSE`.

In addition, would be great if you update the androidx.lifecycle library and use `DefaultLifecycleObserver`, which decreases generated code.

Thank you in advance.

**Comment by motorro** [comment]
@akniyetc, thanks for finding that! Done!
