### ISSUE TITLE
How to use `withUpdateValueCheck`

### ISSUE THREAD

**Issue by CompuGeniusCode** [motorro/AppUpdateWrapper#21]
Hi,
I'm trying to set up a system where it uses Google's priority recommendations:
```
- Minor UI improvements: Low-priority update; request neither a flexible update nor an immediate update. Update only when the user isn't interacting with your app.
- Performance improvements: Medium-priority update; request a flexible update.
- Critical security update: High-priority update; request an immediate update.
```
How do I use `withUpdateValueCheck` to accomplish this?

**Comment by motorro** [comment]
Hi @CompuGenius!
Sorry for the delayed answer - missed github notification :(
Basically you use different breakers to interrupt flexible flow if:
- you have already asked for update within some time before (like with `withInterval`)
- you need to check Google's `AppUpdateInfo` structure to check those `updatePriority` and all that.

At the time the library was created Goggle didn't provide any way to set those properties at Play Store. But it seems they [have](https://developer.android.com/guide/playcore/in-app-updates/kotlin-java#update-priority) the way to determine them now.
Anyway you could implement your own server logic to get the update priority and either run immediate or flexible update (or not to run it at all)

**Comment by motorro** [comment]
P.S. Why use breakers at all? Just to have your (base) activity run flexible updates every time (easier to set up) then use breaker to interrupt

**Comment by CompuGeniusCode** [comment]
I understand what the breakers are for.
How do I implement them with Kotlin? This is very new territory for me.

**Comment by motorro** [comment]
When flexible update runs it gets `AppUpdateInfo` from google and passes it to the [callback](https://github.com/motorro/AppUpdateWrapper/blob/master/appupdatewrapper/src/main/java/com/motorro/appupdatewrapper/UpdateFlowBreaker.kt#L77). There you check the data and return true if you want to proceed with update.

**Comment by CompuGeniusCode** [comment]
Can you send some sample Kotlin of this implementation, please?

**Comment by motorro** [comment]
@CompuGenius, here you go. Check the sample code in the commit above ⬆️

**Comment by CompuGeniusCode** [comment]
I appreciate this!
Is there a way I can set it to be flexible but if it's of a certain priority, change it to be immediate?

**Comment by motorro** [comment]
Mmm... Not by using this library, unfortunately. This one was intended to be used along with your own server logic. Something like that:
1. You run some request to your API providing app version
2. Server responds with something like ERROR_OUTDATED
3. You start immediate update 

Otherwise you run flexible update from time to time to promote new versions to be installed faster.
