### ISSUE TITLE
Show Progress Update Status During Download

### ISSUE THREAD

**Issue by arunxlabs** [motorro/AppUpdateWrapper#23]
When a download is in progress, it would be beneficial to have a feature that shows the progress update status value. This would allow users to see the current progress of their download, enhancing the overall user experience.

**Comment by motorro** [comment]
Hey @arun1890! 
Sorry for the late reply. I thought I have already answered before :)
I've added a progress callback to the view. I hope it works for you.
Fingers crossed, I'll publish it today

**Comment by motorro** [comment]
Released in [v2.1.0](https://github.com/motorro/AppUpdateWrapper/releases/tag/v2.1.0)
