### ISSUE TITLE
Call back when download is in progress

### ISSUE THREAD

**Issue by wbervoets** [motorro/AppUpdateWrapper#6]
When using the flexible flow, is there a callback when the download is in progress? Eg. after the user accepted to install the update in the Play core popup.

I tried updateChecking(), but this is called before the play core update dialog is shown.

Two more questions:
- is there a way to know that the user pressed cancel vs download in the Google play popup? I could use this call back to show a progress spinner/toast ui element that download is in progress for the download case

*Multi activity setup*

when one activity A launches a startFlexibleUpdate(appUpdateManager, A, UpdateFlowBreaker), what happens when the user accepts the update and the download is busy in the background. When I change to activity B and the download finishes then, will it call the "updateReady" callback on activity B automatically? (B also implements AppUpdateView and both A and B use the same appmanager instance & implement onActivityResult). 

At this moment I'm not receiving any callback in activity B, only in activity A. 
I assume I do not need to call startFlexibleUpdate(appUpdateManager, view, UpdateFlowBreaker.alwaysOn()) in Activity B? Or do I?

**Comment by motorro** [comment]
@wbervoets, sorry for the late answer!
I'll try to answer the last question first as it is a core functionality...

> I assume I do not need to call startFlexibleUpdate(appUpdateManager, view, UpdateFlowBreaker.alwaysOn())

No. You need to start the flow anyway. There is no state save between update wrapper instances besides the state that original google library provides. This is done intentionally to try to not diverse with their flow and to be able to switch to immediate update from flexible at any point. Thus, whenever you start a new flow, you get into [update check](/motorro/AppUpdateWrapper/blob/master/appupdatewrapper/src/main/java/com/motorro/appupdatewrapper/FlexibleUpdateState.kt#L133) which eds up in current status processing [here](/motorro/AppUpdateWrapper/blob/master/appupdatewrapper/src/main/java/com/motorro/appupdatewrapper/FlexibleUpdateState.kt#L197). This will effectively switch you to correct state as long as the google-provided status allows to do it. TLDR the library is designed as a fire-and-forget lifecycle-observer that should be run in every activity you plan to support update UI in. 

> When using the flexible flow, is there a callback when the download is in progress? Eg. after the user accepted to install the update in the Play core popup.

No, there is no dedicated callback on download start. But you can start your spinner manually when update consent returns `RESULT_OK`. You may do in in your `onActivityResult` - the place where you pass results to [wrapper](/motorro/AppUpdateWrapper/blob/master/appupdatewrapper/src/main/java/com/motorro/appupdatewrapper/FlexibleUpdateState.kt#L251):
```
// Passes an activity result to wrapper to check for play-core interaction
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if(REQUEST_CODE_UPDATE == requestCode && RESULT_OK == resultCode) {
            // Start your spinner
        }
        if (updateWrapper.checkActivityResult(requestCode, resultCode)) {
            // Result handled and processed
            return
        }
        // Process your request codes
    }
```
Although the constant is `VisibleForTesting` you can use it or suggest a feature for dedicated callback or constant disclosure :)

> is there a way to know that the user pressed cancel vs download in the Google play popup? I could use this call back to show a progress spinner/toast ui element that download is in progress for the download case

When user cancels you get a call to `complete` [here](/motorro/AppUpdateWrapper/blob/master/appupdatewrapper/src/main/java/com/motorro/appupdatewrapper/FlexibleUpdateState.kt#L104). And, again, the solution may be an `onActivityResult` modification as described above.
